const gt15=[
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:true },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
    { name:"aluno01", present:false },
]
console.log